name: fakeplayer
version: '${plugin.version}'
main: io.github.hello09x.fakeplayer.core.Main
api-version: '1.20'
author: hello09x
website: 'https://github.com/tanyaofei/minecraft-fakeplayer'
depend:
  - CommandAPI

permissions:
  fakeplayer.all:
    description: '假人所有基础权限(即将删除, 请替换成 `fakeplayer.basic`)'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.profile
      - fakeplayer.exp
      - fakeplayer.action

  fakeplayer.*:
    description: '假人所有玩家权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.spawn.name
      - fakeplayer.tp
      - fakeplayer.profile
      - fakeplayer.exp
      - fakeplayer.action
      - fakeplayer.cmd

  fakeplayer.basic:
    description: '假人所有基础权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.profile
      - fakeplayer.exp
      - fakeplayer.action

  fakeplayer.spawn:
    description: '拥有 spawn, kill, list, drop, dropinv 命令权限'

  fakeplayer.spawn.location:
    description: '使用 spawn 命令时可以指定出生点'

  fakeplayer.spawn.name:
    description: '使用 spawn 命令时可以指定假人名称'

  fakeplayer.tp:
    description: '拥有 tp, tphere, tps 命令权限'

  fakeplayer.profile:
    description: '拥有 health, exp 命令权限'

  fakeplayer.action:
    description: '拥有 sneak, look, move, jump, attack, use, ride 命令权限'

  fakeplayer.exp:
    description: '拥有 expme 命令权限'

  fakeplayer.cmd:
    description: '拥有控制假人执行配置文件 `allow-commands` 以外命令的权限'

  fakeplayer.admin:
    description: '假人管理员命令权限'
