name: fakeplayer
version: '${plugin.version}'
main: io.github.hello09x.fakeplayer.core.Main
api-version: '1.20'
author: hello09x
website: 'https://github.com/tanyaofei/minecraft-fakeplayer'
depend:
  - CommandAPI

softdepend:
  - OpenInv

permissions:
  # ------ 命令单独权限
  fakeplayer.command.spawn:
    description: 'spawn 命令权限'
  fakeplayer.command.spawn.name:
    description: 'spawn 命令可以指定名称'
  fakeplayer.command.spawn.location:
    description: 'spawn 命令可以指定坐标'
  fakeplayer.command.kill:
    description: 'kill 命令权限'
  fakeplayer.command.list:
    description: 'list 命令权限'
  fakeplayer.command.select:
    description: 'select 权限命令'
  fakeplayer.command.selection:
    description: 'selection 权限命令'
  fakeplayer.command.distance:
    description: 'distance 命令权限'
  fakeplayer.command.drop:
    description: 'drop 命令权限'
  fakeplayer.command.dropstack:
    description: 'dropstack 命令权限'
  fakeplayer.command.dropinv:
    description: 'dropinv 命令权限'
  fakeplayer.command.skin:
    description: 'skin 命令权限'
  fakeplayer.command.invsee:
    description: 'invsee 命令权限'
  fakeplayer.command.status:
    description: 'status 命令权限'
  fakeplayer.command.respawn:
    description: 'respawn 命令权限'
  fakeplayer.command.expme:
    description: 'expme 命令权限'
  fakeplayer.command.tp:
    description: 'tp 命令权限'
  fakeplayer.command.tphere:
    description: 'tphere 命令权限'
  fakeplayer.command.tps:
    description: 'tps 命令权限'
  fakeplayer.command.config:
    description: 'config 命令权限'
  fakeplayer.command.attack:
    description: 'attack 命令权限'
  fakeplayer.command.mine:
    description: 'mine 命令权限'
  fakeplayer.command.use:
    description: 'use 命令权限'
  fakeplayer.command.jump:
    description: 'jump 命令权限'
  fakeplayer.command.sneak:
    description: 'sneak 命令权限'
  fakeplayer.command.look:
    description: 'look 命令权限'
  fakeplayer.command.turn:
    description: 'turn 命令权限'
  fakeplayer.command.move:
    description: 'move 命令权限'
  fakeplayer.command.ride:
    description: 'ride 命令权限'
  fakeplayer.command.swap:
    description: 'swap 命令权限'
  fakeplayer.command.refill:
    description: 'refill 命令权限'
  fakeplayer.command.refill.chest:
    description: '补货时允许从附近箱子里补'
  fakeplayer.command.sleep:
    description: 'sleep 命令权限'
  fakeplayer.command.wakeup:
    description: 'wakeup 命令权限'
  fakeplayer.command.hold:
    description: 'hold 命令权限'
  fakeplayer.command.cmd:
    description: 'cmd 命令权限'

  # ------ 根据命令的分类聚合成一个权限组
  fakeplayer.spawn:
    description: '所有最基本的命令权限'
    children:
      - fakeplayer.command.spawn
      - fakeplayer.command.kill
      - fakeplayer.command.list
      - fakeplayer.command.distance
      - fakeplayer.command.select
      - fakeplayer.command.selection
      - fakeplayer.command.drop
      - fakeplayer.command.dropstack
      - fakeplayer.command.dropinv
      - fakeplayer.command.skin
      - fakeplayer.command.invsee
      - fakeplayer.command.status
      - fakeplayer.command.respawn
      - fakeplayer.command.config

  fakeplayer.tp:
    description: '所有关于传送的命令权限'
    children:
      - fakeplayer.command.tp
      - fakeplayer.command.tphere
      - fakeplayer.command.tps

  fakeplayer.exp:
    description: '所有关于经验值的命令权限'
    children:
      - fakeplayer.command.expme

  fakeplayer.action:
    description: '所有操作假人行为的命令权限'
    children:
      - fakeplayer.command.attack
      - fakeplayer.command.mine
      - fakeplayer.command.use
      - fakeplayer.command.refill
      - fakeplayer.command.refill.chest
      - fakeplayer.command.jump
      - fakeplayer.command.sneak
      - fakeplayer.command.look
      - fakeplayer.command.turn
      - fakeplayer.command.move
      - fakeplayer.command.ride
      - fakeplayer.command.swap
      - fakeplayer.command.sleep
      - fakeplayer.command.wakeup
      - fakeplayer.command.hold

  fakeplayer.cmd:
    description: '假人所有关于命令的权限'
    children:
      - fakeplayer.command.exp

  # ------ 根据使用场景将组权限再次聚合
  fakeplayer.*:
    description: '假人所有权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.exp
      - fakeplayer.action
      - fakeplayer.cmd

  fakeplayer.basic:
    description: '假人所有基础权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.exp
      - fakeplayer.action

  fakeplayer.all:
    description: '假人所有基础权限(即将删除, 请替换成 `fakeplayer.basic`)'
    children:
      - fakeplayer.basic
